### ISSUE TITLE
Record deployment at New Relic

### ISSUE THREAD

**Issue by turadg** [duostack/duostack-client#1]
I use both Duostack and New Relic. I'd be happy if Duostack could [notify New Relic of a deployment](http://support.newrelic.com/kb/docs/recording-deployments-with-the-ruby-agent), the [way Heroku does](http://devcenter.heroku.com/articles/newrelic#what_the_addon_does).

**Comment by tfe** [comment]
Thanks for the issue submission.

The Duostack client itself is not involved with the deployment process (that's all handled by Git and stuff on the platform side), so I'm going to close this issue. We're looking into adding support for this to the platform in the future though.
